document.addEventListener('DOMContentLoaded', () => {
	let eng = [
		'immaculate',
		'keep from',
		'fall apart',
		'seams',
		'crime',
		'come undone',
		'chills',
		'case',
		'point',
		'sense',
		'government',
		'able',
		'are note / aint',
		'faith-departed',
		'crowd',
		'shout',
		'stand your ground',
		'bend',
		'seek',
		'devide',
		'hang',
		'gull / seagull',
		'on my own',
		'heat',
		'windpipe',
		'huff',
		'suffer',
		'suffocate',
		'drown',
		'im about to',
		'resuscitate',
		'snap',
		'lay',
		'stoop',
		'barley',
		'neither',
		'either',
		'sick of',
		'spew',
		'spit',
		'pull',
		'separate',
		'restraint',
		'sidewalk',
		'sencere',
		'pissed',
		'tie',
		'urgent',
		'clearance',
		'retired',
		'similar',
		'mention',
		'suspicions',
		'mess',
		'mole',
		'prick',
		'necessary',
		'sourse',
		'chaps',
		'pleased',
		'leaky',
		'pretend',
		'entertain',
		'contagious',
		'vain',
		'torture',
		'gaze',
		'above',
	];
	let ru = [
		'безупречный',
		'удержаться',
		'развалитьяс на части',
		'швы',
		'преступление',
		'что-то undone',
		'мурашки',
		'дело / случай',
		'точка / смысл',
		'смысл',
		'государство',
		'в состоянии / способен',
		'не',
		'потерявший веру',
		'толпа',
		'кричать',
		'стоять на своем',
		'гнуться',
		'искать',
		'разделять',
		'вешать',
		'чайка',
		'сам по себе',
		'жара',
		'трахея',
		'оскорблять / раздражать',
		'страдать',
		'задыхаться',
		'тонуть',
		'я собирась сделать',
		'реанимировать',
		'щелчок',
		'класть',
		'унижение',
		'едва / еле еле',
		'никто / также не',
		'любой / каждый',
		'устал от',
		'блевать / изрыгать',
		'плевать',
		'тянуть',
		'отдельный',
		'сдержанный',
		'тротуар',
		'честный / искренний',
		'раздраженный',
		'завязывать / галстук',
		'срочно',
		'разрешение',
		'ушел в отставку',
		'похожий',
		'упоминать',
		'подозрение',
		'беспорядок',
		'крот / моль',
		'хер / ничтожество',
		'необходимый',
		'источник',
		'ребята',
		'довольный',
		'дырявый',
		'притворяться',
		'развлекать',
		'заразный',
		'напрасно',
		'пытка',
		'взор / взгляд',
		'выше',
	];

	const title = document.querySelector('.questions-title');
	const subtitle = document.querySelector('.questions-subtitle');
	const btn = document.querySelector('.questions__button');

	const randomInd = (min, max) => {
		let rand = min + Math.random() * (max + 1 - min);
		return Math.floor(rand);
	};

	const btnClick = () => {
		btn.addEventListener('click', () => {
			title.innerHTML = ru[randomInd(0, eng.length - 1)];
		});
	};
	btnClick();
});